version: '3.2'
services:

  db:
    container_name: mvc_db
    image: mysql:5.6.39
    restart: always
    env_file:
      - .env
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password --local-infile --innodb-large-prefix=1 --innodb-file-format=barracuda --innodb-file-format_max=barracuda --innodb-file-per-table=1
    ports:
      - '3307:3307'
    expose:
      - '3307'
    volumes:
      - db:/var/lib/db

volumes:
  db: