#include "openapi.h"

static const char *SWAGGER_UI_HTML =
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"  <meta charset=\"utf-8\">\n"
"  <title>Cats API</title>\n"
"  <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/swagger-ui-dist@5/swagger-ui.css\">\n"
"  <style>body{margin:0}</style>\n"
"</head>\n"
"<body>\n"
"  <div id=\"swagger-ui\"></div>\n"
"  <script src=\"https://cdn.jsdelivr.net/npm/swagger-ui-dist@5/swagger-ui-bundle.js\"></script>\n"
"  <script>\n"
"    window.onload = () => {\n"
"      window.ui = SwaggerUIBundle({\n"
"        url: '/openapi.json',\n"
"        dom_id: '#swagger-ui',\n"
"        deepLinking: true,\n"
"        layout: 'BaseLayout'\n"
"      });\n"
"    };\n"
"  </script>\n"
"</body>\n"
"</html>\n";

static const char *OPENAPI_SPEC =
"{"
  "\"openapi\":\"3.0.3\","
  "\"info\":{"
    "\"title\":\"Cats API\","
    "\"version\":\"0.3.0\","
    "\"description\":\"Tiny CRUD service backed by an in-memory list of cats.\""
  "},"
  "\"paths\":{"
    "\"/cats\":{"
      "\"get\":{"
        "\"summary\":\"List all cats\","
        "\"responses\":{"
          "\"200\":{"
            "\"description\":\"OK\","
            "\"content\":{\"application/json\":{\"schema\":{\"$ref\":\"#/components/schemas/CatList\"}}}"
          "}"
        "}"
      "},"
      "\"post\":{"
        "\"summary\":\"Create a cat\","
        "\"description\":\"id is generated server-side and returned in the response.\","
        "\"requestBody\":{"
          "\"required\":true,"
          "\"content\":{\"application/json\":{\"schema\":{\"$ref\":\"#/components/schemas/CatInput\"}}}"
        "},"
        "\"responses\":{"
          "\"201\":{\"description\":\"Created\",\"content\":{\"application/json\":{\"schema\":{\"$ref\":\"#/components/schemas/CatEnvelope\"}}}},"
          "\"400\":{\"description\":\"Invalid input\",\"content\":{\"application/json\":{\"schema\":{\"$ref\":\"#/components/schemas/Error\"}}}}"
        "}"
      "}"
    "},"
    "\"/cats/{id}\":{"
      "\"parameters\":["
        "{\"in\":\"path\",\"name\":\"id\",\"required\":true,\"schema\":{\"type\":\"integer\",\"minimum\":1}}"
      "],"
      "\"get\":{"
        "\"summary\":\"Get a cat by id\","
        "\"responses\":{"
          "\"200\":{\"description\":\"OK\",\"content\":{\"application/json\":{\"schema\":{\"$ref\":\"#/components/schemas/CatEnvelope\"}}}},"
          "\"404\":{\"description\":\"Not found\",\"content\":{\"application/json\":{\"schema\":{\"$ref\":\"#/components/schemas/Error\"}}}}"
        "}"
      "},"
      "\"put\":{"
        "\"summary\":\"Update a cat\","
        "\"requestBody\":{"
          "\"required\":true,"
          "\"content\":{\"application/json\":{\"schema\":{\"$ref\":\"#/components/schemas/CatInput\"}}}"
        "},"
        "\"responses\":{"
          "\"200\":{\"description\":\"OK\",\"content\":{\"application/json\":{\"schema\":{\"$ref\":\"#/components/schemas/CatEnvelope\"}}}},"
          "\"400\":{\"description\":\"Invalid input\",\"content\":{\"application/json\":{\"schema\":{\"$ref\":\"#/components/schemas/Error\"}}}},"
          "\"404\":{\"description\":\"Not found\",\"content\":{\"application/json\":{\"schema\":{\"$ref\":\"#/components/schemas/Error\"}}}}"
        "}"
      "},"
      "\"delete\":{"
        "\"summary\":\"Delete a cat\","
        "\"responses\":{"
          "\"204\":{\"description\":\"Deleted\"},"
          "\"404\":{\"description\":\"Not found\",\"content\":{\"application/json\":{\"schema\":{\"$ref\":\"#/components/schemas/Error\"}}}}"
        "}"
      "}"
    "}"
  "},"
  "\"components\":{"
    "\"schemas\":{"
      "\"Cat\":{"
        "\"type\":\"object\","
        "\"description\":\"A cat as returned by the API. id is server-generated.\","
        "\"properties\":{"
          "\"id\":{\"type\":\"integer\",\"readOnly\":true,\"example\":1},"
          "\"name\":{\"type\":\"string\",\"example\":\"Whiskers\"},"
          "\"age\":{\"type\":\"integer\",\"minimum\":1,\"example\":3}"
        "},"
        "\"required\":[\"id\",\"name\",\"age\"]"
      "},"
      "\"CatInput\":{"
        "\"type\":\"object\","
        "\"description\":\"Request body for create/update. Never includes id.\","
        "\"properties\":{"
          "\"name\":{\"type\":\"string\",\"example\":\"Luna\"},"
          "\"age\":{\"type\":\"integer\",\"minimum\":1,\"example\":2}"
        "},"
        "\"required\":[\"name\",\"age\"]"
      "},"
      "\"CatEnvelope\":{"
        "\"type\":\"object\","
        "\"properties\":{\"data\":{\"$ref\":\"#/components/schemas/Cat\"}}"
      "},"
      "\"CatList\":{"
        "\"type\":\"object\","
        "\"properties\":{\"data\":{\"type\":\"array\",\"items\":{\"$ref\":\"#/components/schemas/Cat\"}}}"
      "},"
      "\"Error\":{"
        "\"type\":\"object\","
        "\"properties\":{\"error\":{\"type\":\"string\"}}"
      "}"
    "}"
  "}"
"}";

Response *handle_swagger_ui(Request *request) {
    (void)request;
    Response *r = response_new(HTTP_OK);
    if (!r) return NULL;
    response_add_header(r, "Content-Type: text/html; charset=utf-8");
    response_set_body(r, SWAGGER_UI_HTML);
    return r;
}

Response *handle_openapi_json(Request *request) {
    (void)request;
    Response *r = response_new(HTTP_OK);
    if (!r) return NULL;
    response_add_header(r, "Content-Type: application/json; charset=utf-8");
    response_set_body(r, OPENAPI_SPEC);
    return r;
}
